name: Functional Test

on:
  pull_request:
  push:
    branches:
      - develop
      - trunk

jobs:
  functional:
    name: Functional - WP ${{ matrix.wp }} on PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['8.0']
        wp: ['latest']

    services:
      mysql:
        image: mariadb:10.4
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=10s --health-retries=10

    steps:
      - name: Check out source code
        uses: actions/checkout@v2

      - name: Set up PHP environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: '${{ matrix.php }}'
          extensions: gd, imagick, mysql, zip
          coverage: none
          tools: composer

      - name: Install Composer dependencies & cache dependencies
        run: composer install

      - name: Start MySQL server
        run: sudo systemctl start mysql

      - name: Prepare test database
        run: ./bin/install-package-tests.sh
        env:
          WP_CLI_BIN_DIR: '/tmp/wp-cli-phar'
          WP_CLI_CONFIG_PATH: '/tmp/wp-cli-phar/config.yml'

      - name: Check Behat environment
        run: WP_CLI_TEST_DEBUG_BEHAT_ENV=1 composer behat

      - name: Run Tests
        env:
          WP_VERSION: '${{ matrix.wp }}'
          WP_CLI_BIN_DIR: '/tmp/wp-cli-phar'
          WP_CLI_CONFIG_PATH: '/tmp/wp-cli-phar/config.yml'
        run: ./vendor/bin/behat features/load-wp-cli.feature