name: Build Stable branch
on:
  push:
    branches:
    - trunk

jobs:
  release:
    name: Push (merge) to trunk
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build
      run: |
        composer install --no-dev
        composer build-zip
        rm -rf ./release && unzip ${{ github.event.repository.name }}.zip -d ./release
    - name: Release to Stable
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: stable
        FOLDER: release
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MESSAGE: 'Release: ({sha}) {msg}'
