name: Functional Tests

on:
  pull_request: null
  push:
    branches:
      - develop
      - trunk

jobs:
  call-functional-tests:
    name: Functional
    strategy:
      fail-fast: false
      matrix:
        php: ['7.4']
        wp: ['latest']
        api: ['patchstack', 'wordfence', 'wpscan']
    uses: ./.github/workflows/reusable-testing.yml
    with:
      php-version: ${{ matrix.php }}
      wordpress-version: ${{ matrix.wp }}
      api: ${{ matrix.api }}
    secrets: inherit
