name: Functional Tests

on:
  pull_request: null
  push:
    branches:
      - develop
      - trunk

jobs:
  call-functional-tests:
    name: Functional
    strategy:
      fail-fast: false
      matrix:
        php: ['7.4']
        wp: ['latest']
        api: ['patchstack', 'wordfence', 'wpscan']
    uses: ./.github/workflows/reusable-testing.yml
    env:
        PATCHSTACK_API_TOKEN_TOKEN: ${{ secrets.PATCHSTACK_API_TOKEN_TOKEN }}
        WPSCAN_API_TOKEN: ${{ secrets.WPSCAN_API_TOKEN }}
    with:
      php-version: ${{ matrix.php }}
      wordpress-version: ${{ matrix.wp }}
      api: ${{ matrix.api }}
      patchstack-api-token: ${{ env.PATCHSTACK_API_TOKEN_TOKEN }}
      wpscan-api-token: ${{ env.WPSCAN_API_TOKEN }}
