name: Functional Tests

on:
  pull_request: none
  push:
    branches:
      - develop
      - trunk

jobs:
  call-functional-test:
    name: Functional
    strategy:
      fail-fast: false
      matrix:
        php: ['7.4']
        wp: ['latest']
        api: ['patchstack', 'wordfence', 'wpscan']
    uses: ./.github/workflows/reusable-testing.yml
    with:
      php-version: ${{ matrix.php }}
      wordpress-version: ${{ matrix.wp }}
      api: ${{ matrix.api }}
      patchstack-api-token: ${{ secrets.PATCHSTACK_API_TOKEN }}
      wpscan-api-token: ${{ secrets.WPSCAN_API_TOKEN }}

